export { default as Triangle } from './Triangle'
export { default as Circle } from './Circle'
export { default as Square } from './Square'
export { default as Input } from './Input'
export { default as Label } from './Label'
export { default as Text } from './Text'