export { default as TriangleFigure } from './TriangleFigure'
export { default as CircleFigure } from './CircleFigure'
export { default as SquareFigure } from './SquareFigure'
export { default as InputNumber } from './InputNumber'
export { default as InputColor } from './InputColor'
export { default as Label } from './Label'
export { default as Text } from './Text'